FROM amazoncorretto:21

WORKDIR /app

COPY . .

RUN ./gradlew clean build -x test

ENV PROJECT_NAME=discodeit
ENV PROJECT_VERSION=1.2-M8

ENV JVM_OPTS=""

EXPOSE 80

ENTRYPOINT ["sh", "-c", "java $JVM_OPTS -jar build/libs/${PROJECT_NAME}-${PROJECT_VERSION}.jar --server.port=80"]
