spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB:discodeit}
    username: ${POSTGRES_USER:discodeit_user}
    password: ${POSTGRES_PASSWORD:discodeit1234}


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  boot:
    admin:
      client:
        url: http://localhost:9090

logging:
  level:
    # Hibernate SQL
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    org.hibernate.type.descriptor.sql: info

    # Spring Web
    org.springframework.web: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: info


